import type { ReviewViewModel } from "./model.ts";

const frameId = (digit: string): string => digit.repeat(64);

/**
 * Synthetic development data for rendering the shell before the Tauri command
 * bridge is connected. It contains no acquisition path or private metadata.
 */
export const demoReviewModel: ReviewViewModel = {
  activeWorkspace: "frames",
  sessionName: "M31 · Session 01",
  sessionStatus: { tone: "ready", label: "Demo ready" },
  activeRole: "light",
  playing: false,
  reviewSessionReady: false,
  canUndo: false,
  decisionPending: false,
  qualityBatchRunning: false,
  qualityBatchProgress: null,
  selectedFrameId: frameId("b"),
  sharedStretchLabel: "Shared stretch · locked",
  preview: null,
  viewerScale: "fit",
  statisticsPanel: {
    open: false,
    frameId: null,
    frameLabel: null,
    state: "idle",
    statistics: null,
    message: null,
  },
  calibration: {
    state: "ready",
    settings: {
      flatPedestalPolicy: "prefer_matched_dark_then_bias",
      maximumExposureDeltaSeconds: 0.25,
      maximumTemperatureDeltaC: 2,
      maximumLightDarkTemperatureDeltaC: 2,
    },
    plan: {
      schemaVersion: 1,
      manifestSha256: "a".repeat(64),
      planSha256: "b".repeat(64),
      ready: true,
      lightPlan: {
        schemaVersion: 1,
        planSha256: "c".repeat(64),
        ready: true,
        products: [
          {
            groupId: "light-uvir-2s-g120-o30",
            dark: {
              kind: "dark",
              status: "matched",
              selectedGroupId: "dark-2s-g120-o30",
              temperatureBasis: "sensor",
              temperatureDeltaCelsius: 0.4,
              blockingReason: null,
              ambiguousGroupIds: [],
              missingFields: [],
            },
            flat: {
              kind: "flat",
              status: "matched",
              selectedGroupId: "flat-uvir-2s-g120-o30",
              temperatureBasis: null,
              temperatureDeltaCelsius: null,
              blockingReason: null,
              ambiguousGroupIds: [],
              missingFields: [],
            },
            candidates: [
              {
                groupId: "dark-2s-g120-o30",
                kind: "dark",
                status: "compatible",
                temperatureBasis: "sensor",
                temperatureDeltaCelsius: 0.4,
                mismatches: [],
              },
              {
                groupId: "flat-uvir-2s-g120-o30",
                kind: "flat",
                status: "compatible",
                temperatureBasis: null,
                temperatureDeltaCelsius: null,
                mismatches: [],
              },
            ],
          },
        ],
      },
      products: [
        {
          groupId: "dark-2s-g120-o30",
          kind: "dark",
          frameCount: 31,
          camera: "ZWO ASI294MC Pro",
          axes: [4144, 2822],
          exposureSeconds: 2,
          sensorTemperatureCelsius: -10,
          setTemperatureCelsius: -10,
          gain: 120,
          offset: 30,
          binning: { x: 1, y: 1 },
          filter: "UV/IR Cut",
          bayerPattern: "RGGB",
          pedestal: {
            status: "not_applicable",
            selectedGroupId: null,
            exposureDeltaSeconds: null,
            temperatureBasis: null,
            temperatureDeltaCelsius: null,
            blockingReason: null,
            ambiguousGroupIds: [],
          },
          candidates: [],
        },
        {
          groupId: "flat-uvir-2s-g120-o30",
          kind: "flat",
          frameCount: 26,
          camera: "ZWO ASI294MC Pro",
          axes: [4144, 2822],
          exposureSeconds: 2,
          sensorTemperatureCelsius: -10,
          setTemperatureCelsius: -10,
          gain: 120,
          offset: 30,
          binning: { x: 1, y: 1 },
          filter: "UV/IR Cut",
          bayerPattern: "RGGB",
          pedestal: {
            status: "matched_dark",
            selectedGroupId: "dark-2s-g120-o30",
            exposureDeltaSeconds: 0,
            temperatureBasis: "sensor",
            temperatureDeltaCelsius: 0,
            blockingReason: null,
            ambiguousGroupIds: [],
          },
          candidates: [
            {
              groupId: "dark-2s-g120-o30",
              sourceKind: "dark",
              status: "compatible",
              exposureDeltaSeconds: 0,
              temperatureBasis: "sensor",
              temperatureDeltaCelsius: 0,
              mismatches: [],
            },
          ],
        },
      ],
    },
    message: "2 master groups · 1 Light group ready",
    buildSettings: {
      minimumFlatNormalizationSamples: 1_024,
      minimumPositiveFlatMedian: 1e-12,
      tileWidth: 256,
      tileHeight: 256,
      memoryLimitBytes: 1_073_741_824,
    },
    execution: {
      state: "idle",
      outputDirectory: null,
      progress: null,
      result: null,
      message: "Choose an output directory when the plan is ready",
    },
    lightSettings: {
      minimumAbsoluteFlat: 1e-12,
      tileWidth: 256,
      tileHeight: 256,
      memoryLimitBytes: 1_073_741_824,
    },
    lightExecution: {
      state: "idle",
      masterDirectory: null,
      outputDirectory: null,
      progress: null,
      result: null,
      message: "Build the reviewed masters before integrating Lights",
    },
  },
  roles: [
    { role: "bias", label: "Bias", count: 0, unresolved: 0 },
    { role: "dark", label: "Darks", count: 204, unresolved: 0 },
    { role: "flat", label: "Flats", count: 26, unresolved: 0 },
    { role: "light", label: "Lights", count: 10, unresolved: 0 },
  ],
  frames: [
    {
      id: frameId("a"),
      label: "light_0001.fits",
      sourcePath: null,
      exposureSeconds: 60,
      temperatureCelsius: -5.3,
      classificationWarning: null,
      bayerPattern: "rggb",
      qualityState: "ready",
      qualityMessage: "Synthetic diagnostic metrics",
      qualityProfileId: "demo-quality-v1",
      state: "accepted",
      rejectionReason: null,
      metrics: {
        fwhmPixels: 3.21,
        eccentricity: 0.39,
        detectedStars: 842,
        background: 1912.4,
        noise: 18.7,
      },
    },
    {
      id: frameId("b"),
      label: "light_0002.fits",
      sourcePath: null,
      exposureSeconds: 60,
      temperatureCelsius: -4.9,
      classificationWarning: null,
      bayerPattern: "rggb",
      qualityState: "ready",
      qualityMessage: "Synthetic diagnostic metrics",
      qualityProfileId: "demo-quality-v1",
      state: "undecided",
      rejectionReason: null,
      metrics: {
        fwhmPixels: 3.38,
        eccentricity: 0.42,
        detectedStars: 817,
        background: 1921.8,
        noise: 19.1,
      },
    },
    {
      id: frameId("c"),
      label: "light_0003.fits",
      sourcePath: null,
      exposureSeconds: 60,
      temperatureCelsius: -4.9,
      classificationWarning: null,
      bayerPattern: "rggb",
      qualityState: "ready",
      qualityMessage: "Synthetic diagnostic metrics",
      qualityProfileId: "demo-quality-v1",
      state: "rejected",
      rejectionReason: "trailing",
      metrics: {
        fwhmPixels: 5.84,
        eccentricity: 0.71,
        detectedStars: 503,
        background: 1938.2,
        noise: 23.6,
      },
    },
    {
      id: frameId("d"),
      label: "light_0004.fits",
      sourcePath: null,
      exposureSeconds: 60,
      temperatureCelsius: -5.3,
      classificationWarning: null,
      bayerPattern: "rggb",
      qualityState: "ready",
      qualityMessage: "Synthetic diagnostic metrics",
      qualityProfileId: "demo-quality-v1",
      state: "undecided",
      rejectionReason: null,
      metrics: {
        fwhmPixels: 3.46,
        eccentricity: 0.44,
        detectedStars: 791,
        background: 1927.1,
        noise: 19.8,
      },
    },
    {
      id: frameId("e"),
      label: "light_0005.fits",
      sourcePath: null,
      exposureSeconds: 60,
      temperatureCelsius: -5.3,
      classificationWarning: null,
      bayerPattern: "rggb",
      qualityState: "error",
      qualityMessage: "Synthetic metrics unavailable",
      qualityProfileId: null,
      state: "undecided",
      rejectionReason: null,
      metrics: {
        fwhmPixels: null,
        eccentricity: null,
        detectedStars: null,
        background: 1920.9,
        noise: 19.2,
      },
    },
  ],
};
